### ISSUE TITLE
Trouble installing MOLUSCE on Ubuntu 16.04 LTS 

### ISSUE THREAD

**Issue by cuau-cabrera** [nextgis/molusce#15]
Hi group,

I'm working on Qgis wien 2.8 and I've just upgraded my Ubuntu version to 16.04 LTS. When I try to install MOLUSCE I get this error message "cannot import name NavigationToolbar2QTAgg" Does anybody know what is this error message about and how can I fix it?
Thanks for your help!

**Comment by yomlao** [comment]
Same issue here, using QGIS 2.16 under Ubuntu 16.04.
Seems that the problem comes from matplotlib (NavigationToolbar2QTAgg was removed in matplotlib 1.5.0) - see [https://stackoverflow.com/questions/36346183/importerror-cannot-import-name-navigationtoolbar2qtagg/37200183](url)

**Comment by micha-silver** [comment]
I "solved" this by replacing `NavigationToolbar2QTAgg `with `NavigationToolbar2QT` in the import statements in two source files: moluscedialog.py and neuralnetworkwidget.py
